// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLN6gwLI8vLmEPxMWmoNFDUrta_Of0zUE',
    appId: '1:116860536172:web:26d6d65d64f3f7855e1f49',
    messagingSenderId: '116860536172',
    projectId: 'sweepsy-ea4d0',
    authDomain: 'sweepsy-ea4d0.firebaseapp.com',
    storageBucket: 'sweepsy-ea4d0.appspot.com',
    measurementId: 'G-S120B196T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0c_ianag_S88BFU4JU-Cf_xwt06FgPHI',
    appId: '1:116860536172:android:ac8503da3c17c6d35e1f49',
    messagingSenderId: '116860536172',
    projectId: 'sweepsy-ea4d0',
    storageBucket: 'sweepsy-ea4d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxT1tJZR_jZpbTK-_ZyUNJLiCm8rURAg',
    appId: '1:116860536172:ios:f70edef1c7f7c1f15e1f49',
    messagingSenderId: '116860536172',
    projectId: 'sweepsy-ea4d0',
    storageBucket: 'sweepsy-ea4d0.appspot.com',
    iosClientId: '116860536172-9id7ilu7mhpoud51obk8ker286edsjfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquaira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCxT1tJZR_jZpbTK-_ZyUNJLiCm8rURAg',
    appId: '1:116860536172:ios:f70edef1c7f7c1f15e1f49',
    messagingSenderId: '116860536172',
    projectId: 'sweepsy-ea4d0',
    storageBucket: 'sweepsy-ea4d0.appspot.com',
    iosClientId: '116860536172-9id7ilu7mhpoud51obk8ker286edsjfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquaira',
  );
}
